gravatar:
    email: josefrancisco.verdu@gmail.com # email for get your avatar url.
    avatar_size: 500                     # size of the avatar.
osrc:
  username: kikobeats                    # coming soon!
blog:
  url: http://blog.kikobeats.com/rss/    # Your blog feed.
  max_posts: 3                           # Number of posts to fetch.
  image_selector: '#feature-image'       # CSS Selector to get a image for each post.